// <auto-generated />
using System;
using AppMorador.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppMorador.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718230440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppMorador.Domain.Entities.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<Guid>("GravadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GravadorId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Central", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSerie")
                        .IsUnique();

                    b.HasIndex("PropriedadeId");

                    b.ToTable("Centrais");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Gravador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeAcesso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Porta")
                        .HasColumnType("int");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("Gravadores");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CentralId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroSeriePainel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Particao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PropriedadeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StatusResolucao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ZonaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ZonaOuUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CentralId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PropriedadeId", "CreatedAtUtc");

                    b.HasIndex("ZonaId", "CreatedAtUtc");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Propriedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Propriedades");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.RegistroEventoAlarme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResultadoProcessamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RegistrosEventoAlarme");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BloqueadoAteUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.VinculoZonaCamera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("ZonaId");

                    b.ToTable("VinculosZonaCamera");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CentralId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CentralId", "Numero")
                        .IsUnique();

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Camera", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Gravador", "Gravador")
                        .WithMany()
                        .HasForeignKey("GravadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppMorador.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gravador");

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Central", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Gravador", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Central", "Central")
                        .WithMany()
                        .HasForeignKey("CentralId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppMorador.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppMorador.Domain.Entities.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Central");

                    b.Navigation("Propriedade");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Propriedade", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Usuario", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.VinculoZonaCamera", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppMorador.Domain.Entities.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("AppMorador.Domain.Entities.Zona", b =>
                {
                    b.HasOne("AppMorador.Domain.Entities.Central", "Central")
                        .WithMany()
                        .HasForeignKey("CentralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Central");
                });
#pragma warning restore 612, 618
        }
    }
}
